import { SendPhotoOptions } from 'node-telegram-bot-api';
import { TCommand, TFileOptions, TText } from './app.types';
import { Options } from 'html-minifier';

export enum Step {
    START = 0x00,
    PERSONAL_NAME = 0x01,
    BIRTH_DATE = 0x02,
    PASSPORT = 0x03
}

export const Text: TText = {
    [Step.START]: 'Пожалуйста, напишите /start',
    [Step.PERSONAL_NAME]: 'Ваше ФИО, пример: Иванов Иван Иванович',
    [Step.BIRTH_DATE]: 'Ваша Дата рождения, пример: 01.01.1985',
    [Step.PASSPORT]: 'Ваш Паспорт, пример: 65** ***333'
};

export const Command: TCommand = {
    START: /\/start/
};

const photoCaption: string = 'QR-код сертификата вакцинации';

export const sendPhotoOptions: SendPhotoOptions = {
    caption: photoCaption
};

export const fileOptions: TFileOptions = {
    filename: photoCaption,
    contentType: 'image/png'
};

export const minifyDefaultOptions: Options = {
    caseSensitive: false,
    collapseBooleanAttributes: true,
    collapseInlineTagWhitespace: false,
    collapseWhitespace: true,
    conservativeCollapse: false,
    decodeEntities: true,
    html5: true,
    includeAutoGeneratedTags: false,
    keepClosingSlash: false,
    minifyCSS: true,
    minifyJS: true,
    preserveLineBreaks: false,
    preventAttributesEscaping: false,
    processConditionalComments: true,
    processScripts: ['text/html'],
    removeAttributeQuotes: true,
    removeComments: true,
    removeEmptyAttributes: true,
    removeEmptyElements: false,
    removeOptionalTags: true,
    removeRedundantAttributes: true,
    removeScriptTypeAttributes: true,
    removeStyleLinkTypeAttributes: true,
    removeTagWhitespace: true,
    sortAttributes: true,
    sortClassName: true,
    trimCustomFragments: true,
    useShortDoctype: true
};
